basePath: /
definitions:
  types.PatchSubscriptionByIDRequest:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
    type: object
  types.PostCreateSubscriptionRequest:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: My API
  version: "1.0"
paths:
  /subscriptions:
    post:
      consumes:
      - application/json
      description: Create a new subscription and issue their subscriptionID
      parameters:
      - description: login and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.PostCreateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
      summary: Create a new subscription
      tags:
      - subscription
  /subscriptions/{subscription_id}:
    get:
      consumes:
      - application/json
      description: Get a subscription by their subscriptionID
      parameters:
      - description: UUID of the subscription
        format: uuid
        in: path
        name: subscription_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Subscription not found
          schema:
            type: string
      summary: Get a subscription
      tags:
      - subscription
    patch:
      consumes:
      - application/json
      description: Patch a subscription by their subscriptionID
      parameters:
      - description: UUID of the subscription
        format: uuid
        in: path
        name: subscription_id
        required: true
        type: string
      - description: Fields to update
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.PatchSubscriptionByIDRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Subscription not found
          schema:
            type: string
      summary: Patch a subscription
      tags:
      - subscription
swagger: "2.0"
